DEFAULT_EXTENTION = '.jpg'

# DEFAULT_SLIDE_HIGHT = 1190
# DEFAULT_SLIDE_WiDTH = 1684
DEFAULT_SLIDE_WiDTH = 640
DEFAULT_SLIDE_HIGHT = 480

DEFAULT_IMAGE_MODE = 'RGB'
DEFAULT_IMAGE_BACKGROUND = 'white'

# Blocks colors
TITLE_COLOR = 'red'
TEXT_COLOR = 'black'